In [1]:
import random
import numpy as np

In [2]:
def task1():
    array = [random.randint(1, 100) for _ in range(10)]
    max_element = max(array)
    max_index = array.index(max_element)
    print("Array:", array)
    print("Max Element:", max_element, "at Index:", max_index)
task1()

Array: [89, 89, 83, 7, 56, 60, 94, 47, 7, 27]
Max Element: 94 at Index: 6


In [3]:
def task2():
    array = [random.randint(-50, 50) for _ in range(10)]
    even_positive_sum = sum(x for x in array if x > 0 and x % 2 == 0)
    print("Array:", array)
    print("Sum of Even Positive Elements:", even_positive_sum)
task2()

Array: [21, 41, -31, -38, 1, -20, 49, -50, 15, -33]
Sum of Even Positive Elements: 0


In [4]:
def task3():
    array = [random.randint(1, 100) for _ in range(10)]
    avg = sum(array) / len(array)
    less_than_avg = [x for x in array if x < avg]
    print("Array:", array)
    print("Average:", avg)
    print("Elements less than average:", less_than_avg)
task3()

Array: [8, 58, 94, 12, 54, 73, 77, 27, 21, 35]
Average: 45.9
Elements less than average: [8, 12, 27, 21, 35]


In [5]:
def task4():
    array = [random.randint(1, 100) for _ in range(10)]
    first_min, second_min = sorted(array)[:2]
    print("Array:", array)
    print("Two Smallest Elements:", first_min, second_min)

task4()

Array: [81, 25, 18, 68, 18, 15, 20, 20, 39, 17]
Two Smallest Elements: 15 17


In [6]:
def task5():
    array = [random.randint(10, 1000) for _ in range(10)]
    digit_sum = sum(int(digit) for num in array for digit in str(abs(num)))
    print("Array:", array)
    print("Sum of All Digits:", digit_sum)
task5()

Array: [798, 121, 884, 89, 769, 872, 989, 998, 333, 615]
Sum of All Digits: 177


In [7]:
def task6():
    array = [random.randint(-50, 50) for _ in range(10)]
    positive_elements = [x for x in array if x > 0]
    avg_positive = sum(positive_elements) / len(positive_elements) if positive_elements else 0
    print("Array:", array)
    print("Average of Positive Elements:", avg_positive)
task6()

Array: [43, 33, 33, 11, 37, 41, -1, 37, 0, -6]
Average of Positive Elements: 33.57142857142857


In [8]:
def task7():
    array = [random.randint(1, 100) for _ in range(10)]
    min_index, max_index = array.index(min(array)), array.index(max(array))
    array[min_index], array[max_index] = array[max_index], array[min_index]
    print("Modified Array:", array)
task7()

Modified Array: [8, 13, 71, 68, 61, 59, 4, 56, 39, 40]


In [9]:
def task8():
    matrix = np.random.randint(1, 10, (3, 3))
    total_sum = matrix.sum()
    total_product = np.prod(matrix)
    avg = matrix.mean()
    print("Matrix:\n", matrix)
    print("Sum:", total_sum, "Product:", total_product, "Average:", avg)
task8()


Matrix:
 [[2 5 2]
 [7 5 7]
 [7 2 3]]
Sum: 40 Product: 205800 Average: 4.444444444444445


In [10]:
def task9():
    matrix = np.random.randint(1, 10, (3, 3))
    diagonal_sum = np.trace(matrix)
    print("Matrix:\n", matrix)
    print("Sum of Main Diagonal:", diagonal_sum)
task9()

Matrix:
 [[4 7 3]
 [5 4 8]
 [6 3 4]]
Sum of Main Diagonal: 12
